### ISSUE TITLE
ZBX-BROCADE-FC-PORT template not working in zabbix 2.4.7

### ISSUE THREAD

**Issue by naechin91004** [jjmartres/Zabbix#100]
Hello.
Import ZBX-BROCADE-FC-PORT template on zabbix 2.4.7.
But Discovery rule has error "value should be json object"

below is external script export json log.

I check result in https://jsonformatter.curiousconcept.com/

but not work in zabbix.

discovery rule key is 
"advsnmp.discovery[{HOST.HOST},"-v1 -c{$SNMP_COMMUNITY}",.1.3.6.1.4.1.1588.2.1.1.1.6.2.1.37,1.1]"

plz help me
======================================================
{
        "data":[
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "1",
                "{#ADVSNMPVALUE}":"0"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "10",
                "{#ADVSNMPVALUE}":"9"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "11",
                "{#ADVSNMPVALUE}":"10"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "12",
                "{#ADVSNMPVALUE}":"11"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "13",
                "{#ADVSNMPVALUE}":"12"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "14",
                "{#ADVSNMPVALUE}":"13"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "15",
                "{#ADVSNMPVALUE}":"14"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "16",
                "{#ADVSNMPVALUE}":"15"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "17",
                "{#ADVSNMPVALUE}":"16"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "18",
                "{#ADVSNMPVALUE}":"17"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "19",
                "{#ADVSNMPVALUE}":"18"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "2",
                "{#ADVSNMPVALUE}":"1"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "20",
                "{#ADVSNMPVALUE}":"19"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "21",
                "{#ADVSNMPVALUE}":"20"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "22",
                "{#ADVSNMPVALUE}":"21"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "23",
                "{#ADVSNMPVALUE}":"22"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "24",
                "{#ADVSNMPVALUE}":"23"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "25",
                "{#ADVSNMPVALUE}":"24"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "26",
                "{#ADVSNMPVALUE}":"25"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "27",
                "{#ADVSNMPVALUE}":"26"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "28",
                "{#ADVSNMPVALUE}":"27"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "29",
                "{#ADVSNMPVALUE}":"28"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "3",
                "{#ADVSNMPVALUE}":"2"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "30",
                "{#ADVSNMPVALUE}":"29"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "31",
                "{#ADVSNMPVALUE}":"30"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "32",
                "{#ADVSNMPVALUE}":"31"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "33",
                "{#ADVSNMPVALUE}":"32"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "34",
                "{#ADVSNMPVALUE}":"33"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "35",
                "{#ADVSNMPVALUE}":"34"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "36",
                "{#ADVSNMPVALUE}":"35"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "37",
                "{#ADVSNMPVALUE}":"36"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "38",
                "{#ADVSNMPVALUE}":"37"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "39",
                "{#ADVSNMPVALUE}":"38"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "4",
                "{#ADVSNMPVALUE}":"3"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "40",
                "{#ADVSNMPVALUE}":"39"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "41",
                "{#ADVSNMPVALUE}":"40"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "42",
                "{#ADVSNMPVALUE}":"41"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "43",
                "{#ADVSNMPVALUE}":"42"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "44",
                "{#ADVSNMPVALUE}":"43"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "45",
                "{#ADVSNMPVALUE}":"44"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "46",
                "{#ADVSNMPVALUE}":"45"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "47",
                "{#ADVSNMPVALUE}":"46"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "48",
                "{#ADVSNMPVALUE}":"47"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "49",
                "{#ADVSNMPVALUE}":"48"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "5",
                "{#ADVSNMPVALUE}":"4"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "50",
                "{#ADVSNMPVALUE}":"49"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "51",
                "{#ADVSNMPVALUE}":"50"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "52",
                "{#ADVSNMPVALUE}":"51"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "53",
                "{#ADVSNMPVALUE}":"52"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "54",
                "{#ADVSNMPVALUE}":"53"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "55",
                "{#ADVSNMPVALUE}":"54"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "56",
                "{#ADVSNMPVALUE}":"55"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "57",
                "{#ADVSNMPVALUE}":"56"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "58",
                "{#ADVSNMPVALUE}":"57"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "59",
                "{#ADVSNMPVALUE}":"58"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "6",
                "{#ADVSNMPVALUE}":"5"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "60",
                "{#ADVSNMPVALUE}":"59"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "61",
                "{#ADVSNMPVALUE}":"60"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "62",
                "{#ADVSNMPVALUE}":"61"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "63",
                "{#ADVSNMPVALUE}":"62"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "64",
                "{#ADVSNMPVALUE}":"63"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "65",
                "{#ADVSNMPVALUE}":"64"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "66",
                "{#ADVSNMPVALUE}":"65"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "67",
                "{#ADVSNMPVALUE}":"66"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "68",
                "{#ADVSNMPVALUE}":"67"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "69",
                "{#ADVSNMPVALUE}":"68"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "7",
                "{#ADVSNMPVALUE}":"6"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "70",
                "{#ADVSNMPVALUE}":"69"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "71",
                "{#ADVSNMPVALUE}":"70"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "72",
                "{#ADVSNMPVALUE}":"71"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "73",
                "{#ADVSNMPVALUE}":"72"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "74",
                "{#ADVSNMPVALUE}":"73"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "75",
                "{#ADVSNMPVALUE}":"74"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "76",
                "{#ADVSNMPVALUE}":"75"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "77",
                "{#ADVSNMPVALUE}":"76"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "78",
                "{#ADVSNMPVALUE}":"77"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "79",
                "{#ADVSNMPVALUE}":"78"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "8",
                "{#ADVSNMPVALUE}":"7"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "80",
                "{#ADVSNMPVALUE}":"79"
                }       ,
                {
                "{#ADVSNMPINDEX1}": "",
                "{#ADVSNMPINDEX2}": "9",
                "{#ADVSNMPVALUE}":"8"
                }
        ]
}
===============================================

**Comment by naechin91004** [comment]
I solve it

**Comment by jashankochar** [comment]
can u tell how u solved? as am facing same issue
