### ISSUE TITLE
ZBX-CISCO-INTERFACES - Followed the instructions but can't make the template work

### ISSUE THREAD

**Issue by maksokami** [jjmartres/Zabbix#118]
Hello,

I followed the instructions but can't make the ZBX-CISCO-INTERFACES template work. Ruby is installed and working, so as external script. Template applied to the host. I've created an item, but it's not clear what  "Type of information" I should select (selected Text for now).

The host shows 1 Application and 1 Discovery rule, and I don't see a list of discovered interface anywhere.
Is there anything else missing from instructions that I need to do?
Also what does the Macros "-p-|-P-|-pe-|-PE-" stands for? It this for interface filtering? How can I filter interfaces?

zabbix 3.0.1
ruby 1.9.3p194
gem 1.8.23

Thank you

![zbx-3](https://cloud.githubusercontent.com/assets/525382/17098217/a4c60530-527a-11e6-8dba-cc9a276c8345.jpg)
![zbx-2](https://cloud.githubusercontent.com/assets/525382/17098216/a4c4fe56-527a-11e6-9fad-75a4d8e8f659.jpg)
![zbx-1](https://cloud.githubusercontent.com/assets/525382/17098215/a4c43570-527a-11e6-837d-3a9f45b0e0dd.jpg)

**Comment by Ejdesgaard** [comment]
Have a look at the wiki:
https://github.com/jjmartres/Zabbix/wiki/Templates,-MIB%27s-and-LLD-101#intf_regexp

**Comment by maksokami** [comment]
Thanks, that clarified INTF_REGEXP. I removed the value to include all interfaces, but template still doesn't work. Should I use "text" data type for the script item?

**Comment by maksokami** [comment]
I found the problem, I think. SNMP OID syntax changed in 3.0 zabbix version and default value "IF-MIB::ifDescr" no longer works. I wrote it in a new format and discovery started to work:
discovery[{#SNMPVALUE}, IF-MIB::ifDescr]

 This is worth mentioning in the Readme, because this scripts will not work for zabbix >= 3.0 out of the box.

**Comment by maksokami** [comment]
This can be closed now
