### ISSUE TITLE
Zabbix Fortigate templates, Interface traffic

### ISSUE THREAD

**Issue by DanielG27** [jjmartres/Zabbix#126]
Hi,

First of all, thank you for the templates! They are great. One question though, I am currently using the Fortinet templates in Zabbix 3.2 and I can read the memory usage and such but I can't read out the Interfaces traffic. It is able to discover them without a problem but I am not receiving any data. How do I receive data? Is it via if.speed? How would this work in a Debian environment?

Thanks in advance for all your help!

Kind regards,
Daniel

**Comment by mikaelmasson** [comment]
Hi,
I've got the same problem and resolv it with :

Install "snmp-mibs-downloader"  (it's NON FREE package : "deb http://ftp.fr.debian.org/debian/ jessie main non-free contrib" in your sources.list ) : 
#apt-get update
#apt-get install snmp-mibs-downloader

Restart zabbix... And.. It's works!

Mike

**Comment by DanielG27** [comment]
Hi Mike

Thank you for the answer! Everything is now up and running. 

Thanks once again,
Daniel

**Comment by mikaelmasson** [comment]
:+1: 
You're welcome!

**Comment by mikaelmasson** [comment]
Don't forget to close this issue  ;)
