### ISSUE TITLE
Error importing Eaton template

### ISSUE THREAD

**Issue by e9169** [jjmartres/Zabbix#137]
Hi everybody,

While trying to import the eaton template xml into Zabbix I get this error:

Cannot find value map "xupsOutputSource" used for item "Output power source" on "ZBX-POWERWARE-UPS".

Any idea how to solve it, please?

Thank you in advance.

**Comment by xenadmin** [comment]
There is detailed advice in the readme about the Value Maps you have to add. 
https://github.com/jjmartres/Zabbix/tree/master/zbx-templates/zbx-eaton

If you don't know how to ad Value Maps, please refer to the Zabbix Documentation:
https://www.zabbix.com/documentation/3.4/manual/config/items/mapping

**Comment by e9169** [comment]
Thank you, for some reason I though this had to be done after importing the template.
