### ISSUE TITLE
Dell-Powerconnect-interfaces - discovery Doesn't happen

### ISSUE THREAD

**Issue by Ejdesgaard** [jjmartres/Zabbix#19]
First of all, _Awsome work!_ I have used your templates on various catalyst equipment, and it "just works" :+1: 

Now to the problem...
I'm a rookie when it comes to zabbix, so it might be an error from my side, but I have done my best to follow your README's

I have imported the ZBX-DELL-POWERECONNECT-INTERFACES, added the if.speed script and checked the zabbix_server.conf.
the SNMP_COMMUNITY is set to the RO community name and INTF_REGEXP is set as in your example.

But no interfaces are discovered. On the other hand, when I run an snmpwalk on interfaces, i get a positive return:
    snmpwalk -v2c -c public 192.168.1.195 .1.3.6.1.2.1.31.1.1.1.1
    IF-MIB::ifName.1 = STRING: 1/0/1
    IF-MIB::ifName.2 = STRING: 1/0/2
    IF-MIB::ifName.3 = STRING: 1/0/3
    IF-MIB::ifName.4 = STRING: 1/0/4
    IF-MIB::ifName.5 = STRING: 1/0/5
    ...

The if.speed script is also working
./if.speed -d 192.168.1.195 -c public 1
1000000000

Switch config is:
snmp-server community public ro ipaddress [zabbix server]

Edit:
Switch Model: PowerConnect 6248 with 10Gbps modules

**Comment by Thadeu** [comment]
jjmartres, onde eu consigo alterar o INTF_REGEXP Padrão?
by Brasil

**Comment by Thadeu** [comment]
jjmartres,
Consegui resolver o problema, adicionei a REGEXP (1/0/) no {#SNMPVALUE} que fica dentro de Regras de descoberta -> Network Interfaces
